'use client';
import React from 'react';
import dynamic from 'next/dynamic';

// Dynamically import Header and Footer components
const Header = dynamic(() => import('@/components/Header'));
const Footer = dynamic(() => import('@/components/Footer'));

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-20">
        <div className="bg-background p-4 sm:p-6 md:p-8 lg:p-10">
          <div className="max-w-4xl mx-auto bg-card shadow-xl rounded-lg p-6 sm:p-8 md:p-10 lg:p-12">
            <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-6 text-center">
              PollyBot.ai Privacy Policy
            </h1>

            <p className="text-sm sm:text-base text-muted-foreground mb-8 text-center">
              <strong>Effective Date:</strong> January 1st, 2025
            </p>

            <p className="text-foreground mb-6">
              This Privacy Policy describes how PollyBot.ai (&quot;we,&quot;
              &quot;us,&quot; or &quot;our&quot;) collects, uses, and shares
              your information when you use our intelligent AI integration and
              orchestration platform (&quot;Service&quot;). We are committed to protecting
              your privacy and handling your data transparently and securely.
            </p>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              1. Information We Collect
            </h2>
            <p className="text-foreground mb-4">
              We collect various types of information to provide and improve our
              Service:
            </p>
            <ul className="list-disc list-inside text-foreground mb-6 space-y-2">
              <li>
                <strong>Account Information:</strong> When you register for an
                account, we collect personal details such as your name, email
                address, and organization name.
              </li>
              <li>
                <strong>Usage Data:</strong> We automatically collect
                information about how you access and use the Service. This may
                include your IP address, browser type, device information,
                operating system, pages viewed, time spent on pages, and other
                diagnostic data.
              </li>
              <li>
                <strong>Input and Output Content:</strong> As an AI integration
                and orchestration platform, we process content you provide as
                input (&quot;Input&quot;) to the underlying Large Language Models (LLMs)
                and the responses generated by these LLMs (&quot;Output&quot;). We process
                this data to facilitate your requested interactions.
              </li>
              <li>
                <strong>Cookies and Tracking Technologies:</strong> We use
                cookies and similar tracking technologies to track activity on
                our Service and hold certain information. Cookies are files with
                a small amount of data which may include an anonymous unique
                identifier. You can instruct your browser to refuse all cookies
                or to indicate when a cookie is being sent. However, if you do
                not accept cookies, you may not be able to use some portions of
                our Service.
              </li>
            </ul>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              2. How We Use Your Information
            </h2>
            <p className="text-foreground mb-4">
              We use the collected information for various purposes:
            </p>
            <ul className="list-disc list-inside text-foreground mb-6 space-y-2">
              <li>To provide, operate, and maintain our Service.</li>
              <li>To improve, personalize, and expand our Service.</li>
              <li>To understand and analyze how you use our Service.</li>
              <li>
                To develop new products, services, features, and functionality.
              </li>
              <li>
                To communicate with you, either directly or through one of our
                partners, including for customer service, to provide you with
                updates and other information relating to the Service, and for
                marketing and promotional purposes.
              </li>
              <li>To find and prevent fraud.</li>
              <li>
                To comply with legal obligations and protect our legal rights.
              </li>
            </ul>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              3. How We Share Your Information
            </h2>
            <p className="text-foreground mb-4">
              We may share your information in the following situations:
            </p>
            <ul className="list-disc list-inside text-foreground mb-6 space-y-2">
              <li>
                <strong>With LLM Providers:</strong> Your Input is shared with
                third-party Large Language Model providers (e.g., OpenAI) as
                necessary to process your requests and generate Output through
                our Service. We adhere to the data handling policies of these
                providers and encourage you to review their privacy policies.
              </li>
              <li>
                <strong>With Service Providers:</strong> We may share your
                information with third-party vendors, consultants, and other
                service providers who perform services for us or on our behalf,
                such as hosting, data analysis, email delivery, customer
                service, and marketing assistance.
              </li>
              <li>
                <strong>For Legal Requirements:</strong> We may disclose your
                information if required to do so by law or in response to valid
                requests by public authorities (e.g., a court order or a
                government agency request).
              </li>
              <li>
                <strong>Business Transfers:</strong> In connection with, or
                during negotiations of, any merger, sale of company assets,
                financing, or acquisition of all or a portion of our business to
                another company.
              </li>
              <li>
                <strong>With Your Consent:</strong> We may disclose your
                personal information for any other purpose with your consent.
              </li>
            </ul>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              4. Data Retention
            </h2>
            <p className="text-foreground mb-6">
              We retain your personal information only for as long as is
              necessary for the purposes set out in this Privacy Policy, unless
              a longer retention period is required or permitted by law (such as
              tax, accounting, or other legal requirements). When we have no
              ongoing legitimate business need to process your personal
              information, we will either delete or anonymize it, or, if this is
              not possible (for example, because your personal information has
              been stored in backup archives), then we will securely store your
              personal information and isolate it from any further processing
              until deletion is possible.
            </p>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              5. Your Data Protection Rights
            </h2>
            <p className="text-foreground mb-4">
              Depending on your location, you may have the following rights
              regarding your personal information:
            </p>
            <ul className="list-disc list-inside text-foreground mb-6 space-y-2">
              <li>
                <strong>Right to Access:</strong> You have the right to request
                copies of your personal data.
              </li>
              <li>
                <strong>Right to Rectification:</strong> You have the right to
                request that we correct any information you believe is
                inaccurate or complete information you believe is incomplete.
              </li>
              <li>
                <strong>Right to Erasure (Right to be Forgotten):</strong> You
                have the right to request that we erase your personal data,
                under certain conditions.
              </li>
              <li>
                <strong>Right to Restrict Processing:</strong> You have the
                right to request that we restrict the processing of your
                personal data, under certain conditions.
              </li>
              <li>
                <strong>Right to Object to Processing:</strong> You have the
                right to object to our processing of your personal data, under
                certain conditions.
              </li>
              <li>
                <strong>Right to Data Portability:</strong> You have the right
                to request that we transfer the data that we have collected to
                another organization, or directly to you, under certain
                conditions.
              </li>
              <li>
                <strong>Right to Withdraw Consent:</strong> Where we rely on
                your consent to process your personal information, you have the
                right to withdraw that consent at any time. This will not affect
                the lawfulness of processing before its withdrawal.
              </li>
              <li>
                <strong>Right to Lodge a Complaint:</strong> If you are in the
                European Economic Area (EEA), UK, or Australia, you have the
                right to lodge a complaint with a supervisory authority if you
                believe your data protection rights have been violated.
              </li>
            </ul>
            <p className="text-foreground mb-6">
              To exercise any of these rights, please contact us using the
              details provided in the &quot;Contact&quot; section below. We will respond
              to your request in accordance with applicable data protection
              laws.
            </p>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              6. International Data Transfers
            </h2>
            <p className="text-foreground mb-6">
              Your information, including personal data, may be transferred to
              and maintained on computers located outside of your state,
              province, country, or other governmental jurisdiction where the
              data protection laws may differ from those of your jurisdiction.
            </p>
            <p className="text-foreground mb-6">
              If you are located outside the United States and choose to provide
              information to us, please note that we transfer the data,
              including personal data, to the United States and process it
              there. We will take all steps reasonably necessary to ensure that
              your data is treated securely and in accordance with this Privacy
              Policy and no transfer of your personal data will take place to an
              organization or a country unless there are adequate controls in
              place including the security of your data and other personal
              information.
            </p>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              7. Security of Your Information
            </h2>
            <p className="text-foreground mb-6">
              The security of your personal information is important to us. We
              implement reasonable administrative, technical, and physical
              safeguards designed to protect the personal information we collect
              and process. However, no method of transmission over the Internet,
              or method of electronic storage, is 100% secure. While we strive
              to use commercially acceptable means to protect your personal
              information, we cannot guarantee its absolute security.
            </p>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              8. Children&quot;s Privacy
            </h2>
            <p className="text-foreground mb-6">
              Our Service is not intended for use by anyone under the age of 13
              (&quot;Children&quot;). We do not knowingly collect personally identifiable
              information from anyone under the age of 13. If you are a parent
              or guardian and you are aware that your child has provided us with
              personal data, please contact us. If we become aware that we have
              collected personal data from children without verification of
              parental consent, we take steps to remove that information from
              our servers.
            </p>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              9. Changes to This Privacy Policy
            </h2>
            <p className="text-foreground mb-6">
              We may update our Privacy Policy from time to time. We will notify
              you of any changes by posting the new Privacy Policy on this page.
              We will let you know via email and/or a prominent notice on our
              Service, prior to the change becoming effective and update the
              &quot;Effective Date&quot; at the top of this Privacy Policy. You are
              advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>

            <h2 className="text-xl sm:text-2xl font-semibold text-foreground mb-4 pt-4 border-t border-border">
              10. Contact Us
            </h2>
            <p className="text-foreground mb-6">
              If you have any questions about this Privacy Policy, please
              contact us:
            </p>
            <p className="text-foreground mb-6">
              <strong>Email:</strong> support@pollybot.ai
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
